#!/bin/bash
# Injects the Miro execution-trace & knowledge-corpus scripts into LibreChat.
# Idempotent — strips any previous injection before re-injecting.
#
# What it does:
#   1. Copies trace-page.html and knowledge-page.html into LibreChat's
#      client/dist/ so they're served as static files.
#   2. Injects miro-trace.js into index.html BEFORE the first <script
#      type="module"> tag.
#   3. Configures nginx to reverse-proxy /miro-trace/* to the Miro proxy's
#      trace REST endpoint (port 9951).  This is required because the
#      client-side JS polls /miro-trace/latest for trace data.
#
# Usage:  bash patches/inject-miro-trace.sh /opt/LibreChat [MIRO_PROXY_PORT]
#
# IMPORTANT: After running this script you MUST restart LibreChat — it caches
# index.html in memory at startup.

set -euo pipefail

LIBRECHAT_DIR="${1:-/opt/LibreChat}"
MIRO_PORT="${2:-9951}"
INDEX_HTML="$LIBRECHAT_DIR/client/dist/index.html"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

TRACE_JS="$SCRIPT_DIR/miro-trace.js"
TRACE_PAGE="$SCRIPT_DIR/trace-page.html"
KNOWLEDGE_PAGE="$SCRIPT_DIR/knowledge-page.html"

# ── Validate inputs ─────────────────────────────────────────────────────
for f in "$INDEX_HTML" "$TRACE_JS" "$TRACE_PAGE" "$KNOWLEDGE_PAGE"; do
  if [ ! -f "$f" ]; then
    echo "ERROR: $f not found" >&2
    exit 1
  fi
done

# ── Copy HTML pages into dist/ ──────────────────────────────────────────
cp "$TRACE_PAGE" "$LIBRECHAT_DIR/client/dist/trace.html"
cp "$KNOWLEDGE_PAGE" "$LIBRECHAT_DIR/client/dist/knowledge.html"
echo "Copied trace.html and knowledge.html into $LIBRECHAT_DIR/client/dist/"

# ── Strip any previous miro-trace injection ─────────────────────────────
python3 -c "
import re
html = open('$INDEX_HTML').read()
html = re.sub(r'<script>\s*/\*\*\s*\*\s*Miro Execution Trace.*?</script>\s*', '', html, flags=re.DOTALL)
open('$INDEX_HTML', 'w').write(html)
"

# ── Inject miro-trace.js BEFORE the first <script type="module"> ────────
#
# LibreChat's bundled JS (ES modules) captures window.fetch at import time.
# If we inject after the modules, our fetch monkey-patch is never called.
# Injecting before the first module ensures window.fetch is patched before
# any module can capture a stale reference.
python3 -c "
import re, sys
js = open('$TRACE_JS').read()
html = open('$INDEX_HTML').read()
tag = '<script>' + js + '</script>\n'
# Insert before the first <script type=\"module\">
m = re.search(r'<script type=\"module\"', html)
if m:
    html = html[:m.start()] + tag + html[m.start():]
else:
    # Fallback: inject before </head>
    html = html.replace('</head>', tag + '</head>', 1)
open('$INDEX_HTML', 'w').write(html)
"

echo "Miro trace script injected into $INDEX_HTML"

# ── Configure nginx as reverse-proxy in front of LibreChat ────────────
#
# The client-side miro-trace.js polls /miro-trace/latest for trace data.
# Since the Miro proxy (port 9951) is not exposed externally, we put nginx
# on port 3000 (where Cloudflare Tunnel / external traffic arrives) and
# move LibreChat to port 3001.  Nginx proxies:
#   /miro-trace/*  → Miro proxy trace REST endpoint (port 9951)
#   /*             → LibreChat (port 3001)
#
# This is idempotent — if LibreChat is already on 3001 or nginx is already
# configured, it just updates the config.

LIBRECHAT_BACKEND_PORT=3001

# Check if LibreChat is currently on port 3000 and needs to be moved
if ss -tlnp 2>/dev/null | grep -q ":3000.*node"; then
    echo "Moving LibreChat from port 3000 to port ${LIBRECHAT_BACKEND_PORT}..."
    # Update .env to use the new port
    if [ -f /opt/.env ]; then
        # Remove any existing PORT line and add the new one
        sed -i '/^PORT=/d' /opt/.env
        echo "PORT=${LIBRECHAT_BACKEND_PORT}" >> /opt/.env
    fi
fi

NGINX_CONF="/etc/nginx/conf.d/miro-trace.conf"
cat > "$NGINX_CONF" << NGINX_EOF
# Miro trace side-channel + LibreChat reverse proxy.
# Auto-generated by inject-miro-trace.sh — do not edit manually.
#
# nginx sits on port 3000 (where external traffic arrives via Cloudflare
# Tunnel).  LibreChat runs on port ${LIBRECHAT_BACKEND_PORT} behind nginx.
server {
    listen 3000;
    server_name _;

    # Proxy /miro-trace/* to Miro proxy's trace REST endpoint
    location /miro-trace/ {
        proxy_pass http://127.0.0.1:${MIRO_PORT}/trace/;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
    }

    # Everything else goes to LibreChat
    location / {
        proxy_pass http://127.0.0.1:${LIBRECHAT_BACKEND_PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 600s;
    }
}
NGINX_EOF

# Disable the default nginx site (it listens on port 80, no conflict,
# but let's keep things clean)
rm -f /etc/nginx/sites-enabled/default 2>/dev/null || true

# Test and reload nginx
if nginx -t 2>/dev/null; then
    nginx -s reload 2>/dev/null || systemctl reload nginx 2>/dev/null || true
    echo "Nginx configured on port 3000: /miro-trace/* → localhost:${MIRO_PORT}/trace/*"
else
    echo "WARNING: nginx config test failed — trace polling will not work" >&2
    echo "You may need to install nginx: apt-get install -y nginx" >&2
fi

echo "NOTE: Restart LibreChat on port ${LIBRECHAT_BACKEND_PORT} for changes to take effect."
echo "      Set PORT=${LIBRECHAT_BACKEND_PORT} in /opt/.env before restarting."
